<!-- This file automatically generated by ParseAutoconfTexinfo utility -->
<!--
    This file is protected by Copyright.
    Please refer to the COPYRIGHT file distributed with this source distribution.

    This file is part of REDHAWK IDE.

    All rights reserved.  This program and the accompanying materials are made available under
    the terms of the Eclipse Public License v1.0 which accompanies this distribution, and is available at
    http://www.eclipse.org/legal/epl-v10.html.
-->
<!-- cvs -d:pserver:anonymous@sources.redhat.com:/cvs/eclipse \        -->
<!--   co autotools/ParseTexinfo                                       -->
<!DOCTYPE macros [

  <!ELEMENT macros (macro)*>

  <!ELEMENT macro (prototype*,synopsis)>
  <!ATTLIST macro
    id ID #REQUIRED
  >

  <!ELEMENT synopsis     (#PCDATA)*>

  <!ELEMENT prototype    (parameter+)?>

  <!ELEMENT parameter (#PCDATA)*>
  <!ATTLIST parameter
    content CDATA #REQUIRED
  >

]>

<macros>
  <macro id="AC_INIT">
      <prototype>
        <parameter content="package"/>
        <parameter content="version"/>
        <parameter content="[bug-report]"/>
        <parameter content="[tarname]"/>
      </prototype>
        <synopsis>
          Process any command-line arguments and perform various
         initializations and verifications.&lt;/P&gt;&lt;P&gt;

         Set the name of the &lt;VAR&gt;package&lt;/VAR&gt; and its
         &lt;VAR&gt;version&lt;/VAR&gt;.  These are typically used in
         &lt;samp&gt;--version&lt;/samp&gt; support, including that of
         &lt;CODE&gt;configure&lt;/CODE&gt;.  The optional argument
         &lt;VAR&gt;bug-report&lt;/VAR&gt; should be the email to which
         users should send bug reports.  The package
         &lt;VAR&gt;tarname&lt;/VAR&gt; differs from
         &lt;VAR&gt;package&lt;/VAR&gt;: the latter designates the full
         package name (e.g., &lt;samp&gt;GNU Autoconf&lt;/samp&gt;),
         while the former is meant for distribution tar ball names (e.g.,
         &lt;samp&gt;autoconf&lt;/samp&gt;).  It defaults to
         &lt;VAR&gt;package&lt;/VAR&gt; with &lt;samp&gt;GNU
         &lt;/samp&gt; stripped, lower-cased, and all characters other
         than alphanumerics and underscores are changed to
         &lt;samp&gt;-&lt;/samp&gt;.&lt;/P&gt;&lt;P&gt;

         It is preferable that the arguments of
         &lt;CODE&gt;AC_INIT&lt;/CODE&gt; be static, i.e., there should
         not be any shell computation, but they can be computed by M4.&lt;/P&gt;&lt;P&gt;

         The following M4 macros (e.g.,
         &lt;CODE&gt;AC_PACKAGE_NAME&lt;/CODE&gt;), output variables
         (e.g., &lt;CODE&gt;PACKAGE_NAME&lt;/CODE&gt;), and preprocessor
         symbols (e.g., &lt;CODE&gt;PACKAGE_NAME&lt;/CODE&gt;) are
         defined by &lt;CODE&gt;AC_INIT&lt;/CODE&gt;:&lt;/P&gt;&lt;P&gt;

         &lt;DL&gt;  &lt;DT&gt;&lt;CODE&gt;AC_PACKAGE_NAME&lt;/CODE&gt;,
         &lt;CODE&gt;PACKAGE_NAME&lt;/CODE&gt; &lt;DD&gt;    Exactly
         &lt;VAR&gt;package&lt;/VAR&gt;.&lt;/P&gt;&lt;P&gt;

         &lt;DT&gt;&lt;CODE&gt;AC_PACKAGE_TARNAME&lt;/CODE&gt;,
         &lt;CODE&gt;PACKAGE_TARNAME&lt;/CODE&gt; &lt;DD&gt;    Exactly
         &lt;VAR&gt;tarname&lt;/VAR&gt;.&lt;/P&gt;&lt;P&gt;

         &lt;DT&gt;&lt;CODE&gt;AC_PACKAGE_VERSION&lt;/CODE&gt;,
         &lt;CODE&gt;PACKAGE_VERSION&lt;/CODE&gt; &lt;DD&gt;    Exactly
         &lt;VAR&gt;version&lt;/VAR&gt;.&lt;/P&gt;&lt;P&gt;

         &lt;DT&gt;&lt;CODE&gt;AC_PACKAGE_STRING&lt;/CODE&gt;,
         &lt;CODE&gt;PACKAGE_STRING&lt;/CODE&gt; &lt;DD&gt;    Exactly
         &lt;samp&gt;&lt;VAR&gt;package&lt;/VAR&gt;
         &lt;VAR&gt;version&lt;/VAR&gt;&lt;/samp&gt;.&lt;/P&gt;&lt;P&gt;

         &lt;DT&gt;&lt;CODE&gt;AC_PACKAGE_BUGREPORT&lt;/CODE&gt;,
         &lt;CODE&gt;PACKAGE_BUGREPORT&lt;/CODE&gt; &lt;DD&gt;    Exactly
         &lt;VAR&gt;bug-report&lt;/VAR&gt;. &lt;/DL&gt;
        </synopsis>
  </macro>
  <macro id="AC_PREREQ">
      <prototype>
        <parameter content="version"/>
      </prototype>
        <synopsis>
           Ensure that a recent enough version of Autoconf is being used.
          If the version of Autoconf being used to create
         &lt;CODE&gt;configure&lt;/CODE&gt; is earlier than
         &lt;VAR&gt;version&lt;/VAR&gt;, print an error message to the
         standard error output and exit with failure (exit status is 63).
          For example:&lt;/P&gt;&lt;P&gt;

         &lt;TABLE&gt;&lt;tr&gt;&lt;td&gt;&amp;nbsp;&lt;/td&gt;&lt;td
         class=example&gt;&lt;pre&gt; AC_PREREQ(VERSION)
         &lt;/pre&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;/P&gt;&lt;P&gt;

         This macro is the only macro that may be used before
         &lt;CODE&gt;AC_INIT&lt;/CODE&gt;, but for consistency, you are
         invited not to do so.
        </synopsis>
  </macro>
  <macro id="AC_COPYRIGHT">
      <prototype>
        <parameter content="copyright-notice"/>
      </prototype>
        <synopsis>
           Notice State that, in addition to the Free Software
         Foundation's copyright on the Autoconf macros, parts of your
         &lt;CODE&gt;configure&lt;/CODE&gt; are covered by the
         &lt;VAR&gt;copyright-notice&lt;/VAR&gt;.&lt;/P&gt;&lt;P&gt;

         The &lt;VAR&gt;copyright-notice&lt;/VAR&gt; will show up in both
         the head of &lt;CODE&gt;configure&lt;/CODE&gt; and in
         &lt;samp&gt;configure --version&lt;/samp&gt;.
        </synopsis>
  </macro>
  <macro id="AC_REVISION">
      <prototype>
        <parameter content="revision-info"/>
      </prototype>
        <synopsis>
           Copy revision stamp &lt;VAR&gt;revision-info&lt;/VAR&gt; into
         the &lt;CODE&gt;configure&lt;/CODE&gt; script, with any dollar
         signs or double-quotes removed.  This macro lets you put a
         revision stamp from &lt;TT&gt;configure.ac&lt;/TT&gt; into
         &lt;CODE&gt;configure&lt;/CODE&gt; without RCS or CVS changing
         it when you check in &lt;CODE&gt;configure&lt;/CODE&gt;.  That
         way, you can determine easily which revision of
         &lt;TT&gt;configure.ac&lt;/TT&gt; a particular
         &lt;CODE&gt;configure&lt;/CODE&gt; corresponds to.&lt;/P&gt;&lt;P&gt;

         For example, this line in &lt;TT&gt;configure.ac&lt;/TT&gt;:&lt;/P&gt;&lt;P&gt;

         &lt;TABLE&gt;&lt;tr&gt;&lt;td&gt;&amp;nbsp;&lt;/td&gt;&lt;td
         class=example&gt;&lt;pre&gt; AC_REVISION($Revision: 1.1 $)
         &lt;/pre&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;/P&gt;&lt;P&gt;

          produces this in &lt;CODE&gt;configure&lt;/CODE&gt;:&lt;/P&gt;&lt;P&gt;

         &lt;TABLE&gt;&lt;tr&gt;&lt;td&gt;&amp;nbsp;&lt;/td&gt;&lt;td
         class=example&gt;&lt;pre&gt; #! /bin/sh # From configure.ac
         Revision: 1.30 &lt;/pre&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;
        </synopsis>
  </macro>
  <macro id="AC_CONFIG_SRCDIR">
      <prototype>
        <parameter content="unique-file-in-source-dir"/>
      </prototype>
        <synopsis>
          &lt;VAR&gt;unique-file-in-source-dir&lt;/VAR&gt; is some file
         that is in the package's source directory;
         &lt;CODE&gt;configure&lt;/CODE&gt; checks for this file's
         existence to make sure that the directory that it is told
         contains the source code in fact does.  Occasionally people
         accidentally specify the wrong directory with
         &lt;samp&gt;--srcdir&lt;/samp&gt;; this is a safety check.  ,
         for more information.
        </synopsis>
  </macro>
  <macro id="AC_CONFIG_AUX_DIR">
      <prototype>
        <parameter content="dir"/>
      </prototype>
        <synopsis>
          Use the auxiliary build tools (e.g.,
         &lt;TT&gt;install-sh&lt;/TT&gt;,
         &lt;TT&gt;config.sub&lt;/TT&gt;,
         &lt;TT&gt;config.guess&lt;/TT&gt;, Cygnus
         &lt;CODE&gt;configure&lt;/CODE&gt;, Automake and Libtool scripts
         etc.) that are in directory &lt;VAR&gt;dir&lt;/VAR&gt;. These
         are auxiliary files used in configuration. 
         &lt;VAR&gt;dir&lt;/VAR&gt; can be either absolute or relative to
         &lt;TT&gt;&lt;VAR&gt;srcdir&lt;/VAR&gt;&lt;/TT&gt;.  The default
         is &lt;TT&gt;&lt;VAR&gt;srcdir&lt;/VAR&gt;&lt;/TT&gt; or
         &lt;TT&gt;&lt;VAR&gt;srcdir&lt;/VAR&gt;/..&lt;/TT&gt; or
         &lt;TT&gt;&lt;VAR&gt;srcdir&lt;/VAR&gt;/../..&lt;/TT&gt;,
         whichever is the first that contains
         &lt;TT&gt;install-sh&lt;/TT&gt;.  The other files are not
         checked for, so that using
         &lt;CODE&gt;AC_PROG_INSTALL&lt;/CODE&gt; does not automatically
         require distributing the other auxiliary files.  It checks for
         &lt;TT&gt;install.sh&lt;/TT&gt; also, but that name is obsolete
         because some &lt;CODE&gt;make&lt;/CODE&gt; have a rule that
         creates &lt;TT&gt;install&lt;/TT&gt; from it if there is no
         &lt;TT&gt;Makefile&lt;/TT&gt;.
        </synopsis>
  </macro>
  <macro id="AC_CONFIG_MACRO_DIR">
      <prototype>
        <parameter content="dir"/>
      </prototype>
        <synopsis>
          Future versions of &lt;CODE&gt;autopoint&lt;/CODE&gt;,
         &lt;CODE&gt;libtoolize&lt;/CODE&gt;,
         &lt;CODE&gt;aclocal&lt;/CODE&gt; and
         &lt;CODE&gt;autoreconf&lt;/CODE&gt; will use directory
         &lt;VAR&gt;dir&lt;/VAR&gt; as the location of additional local
         Autoconf macros.  Be sure to call this macro directly from
         &lt;TT&gt;configure.ac&lt;/TT&gt; so that tools that install
         macros for &lt;CODE&gt;aclocal&lt;/CODE&gt; can find the
         declaration before &lt;samp&gt;--trace&lt;/samp&gt; can be
         called safely.
        </synopsis>
  </macro>
  <macro id="AC_OUTPUT">
      <prototype>
      </prototype>
        <synopsis>
           Generate &lt;TT&gt;config.status&lt;/TT&gt; and launch it. 
         Call this macro once, at the end of
         &lt;TT&gt;configure.ac&lt;/TT&gt;.&lt;/P&gt;&lt;P&gt;

         &lt;TT&gt;config.status&lt;/TT&gt; will perform all the
         configuration actions: all the output files (see Configuration
         Files, macro &lt;CODE&gt;AC_CONFIG_FILES&lt;/CODE&gt;), header
         files (see Configuration Headers, macro
         &lt;CODE&gt;AC_CONFIG_HEADERS&lt;/CODE&gt;), commands (see
         Configuration Commands, macro
         &lt;CODE&gt;AC_CONFIG_COMMANDS&lt;/CODE&gt;), links (see
         Configuration Links, macro
         &lt;CODE&gt;AC_CONFIG_LINKS&lt;/CODE&gt;), subdirectories to
         configure (see Subdirectories, macro
         &lt;CODE&gt;AC_CONFIG_SUBDIRS&lt;/CODE&gt;) are honored.&lt;/P&gt;&lt;P&gt;

         The location of your &lt;CODE&gt;AC_OUTPUT&lt;/CODE&gt;
         invocation is the exact point where configuration actions are
         taken: any code afterwards will be executed by
         &lt;CODE&gt;configure&lt;/CODE&gt; once
         &lt;CODE&gt;config.status&lt;/CODE&gt; was run.  If you want to
         bind actions to &lt;CODE&gt;config.status&lt;/CODE&gt; itself
         (independently of whether &lt;CODE&gt;configure&lt;/CODE&gt; is
         being run), see Configuration Commands, , Running Arbitrary
         Configuration Commands.
        </synopsis>
  </macro>
  <macro id="AC_PROG_MAKE_SET">
      <prototype>
      </prototype>
        <synopsis>
           If &lt;CODE&gt;make&lt;/CODE&gt; predefines the Make variable
         &lt;CODE&gt;MAKE&lt;/CODE&gt;, define output variable
         &lt;CODE&gt;SET_MAKE&lt;/CODE&gt; to be empty.  Otherwise,
         define &lt;CODE&gt;SET_MAKE&lt;/CODE&gt; to contain
         &lt;samp&gt;MAKE=make&lt;/samp&gt;.  Calls
         &lt;CODE&gt;AC_SUBST&lt;/CODE&gt; for
         &lt;CODE&gt;SET_MAKE&lt;/CODE&gt;.
        </synopsis>
  </macro>
  <macro id="AC_CONFIG_FILES">
      <prototype>
        <parameter content="file..."/>
        <parameter content="[cmds]"/>
        <parameter content="[init-cmds]"/>
      </prototype>
        <synopsis>
          Make &lt;CODE&gt;AC_OUTPUT&lt;/CODE&gt; create each
         &lt;TT&gt;&lt;VAR&gt;file&lt;/VAR&gt;&lt;/TT&gt; by copying an
         input file (by default
         &lt;TT&gt;&lt;VAR&gt;file&lt;/VAR&gt;.in&lt;/TT&gt;),
         substituting the output variable values. This macro is one of
         the instantiating macros; see Configuration Actions.  , for more
         information on using output variables.  , for more information
         on creating them.  This macro creates the directory that the
         file is in if it doesn't exist.  Usually,
         &lt;TT&gt;Makefile&lt;/TT&gt;s are created this way, but other
         files, such as &lt;TT&gt;.gdbinit&lt;/TT&gt;, can be specified
         as well.&lt;/P&gt;&lt;P&gt;

         Typical calls to &lt;CODE&gt;AC_CONFIG_FILES&lt;/CODE&gt; look
         like this:&lt;/P&gt;&lt;P&gt;

         &lt;TABLE&gt;&lt;tr&gt;&lt;td&gt;&amp;nbsp;&lt;/td&gt;&lt;td
         class=example&gt;&lt;pre&gt; AC_CONFIG_FILES([Makefile
         src/Makefile man/Makefile X/Imakefile])
         AC_CONFIG_FILES([autoconf], [chmod +x autoconf])
         &lt;/pre&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;/P&gt;&lt;P&gt;

         You can override an input file name by appending to
         &lt;VAR&gt;file&lt;/VAR&gt; a colon-separated list of input
         files.  Examples:&lt;/P&gt;&lt;P&gt;

         &lt;TABLE&gt;&lt;tr&gt;&lt;td&gt;&amp;nbsp;&lt;/td&gt;&lt;td
         class=example&gt;&lt;pre&gt;
         AC_CONFIG_FILES([Makefile:boiler/top.mk:boiler/bot.mk]          
               [lib/Makefile:boiler/lib.mk])
         &lt;/pre&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;/P&gt;&lt;P&gt;

          Doing this allows you to keep your file names acceptable to
         MS-DOS, or to prepend and/or append boilerplate to the file.
        </synopsis>
  </macro>
  <macro id="AC_CONFIG_HEADERS">
      <prototype>
        <parameter content="header ..."/>
        <parameter content="[cmds]"/>
        <parameter content="[init-cmds]"/>
      </prototype>
        <synopsis>
           This macro is one of the instantiating macros; see
         Configuration Actions.  Make &lt;CODE&gt;AC_OUTPUT&lt;/CODE&gt;
         create the file(s) in the whitespace-separated list
         &lt;VAR&gt;header&lt;/VAR&gt; containing C preprocessor
         &lt;CODE&gt;#define&lt;/CODE&gt; statements, and replace
         &lt;samp&gt;@@DEFS@@&lt;/samp&gt; in generated files with
         &lt;samp&gt;-DHAVE_CONFIG_H&lt;/samp&gt; instead of the value of
         &lt;CODE&gt;DEFS&lt;/CODE&gt;. The usual name for
         &lt;VAR&gt;header&lt;/VAR&gt; is &lt;TT&gt;config.h&lt;/TT&gt;.&lt;/P&gt;&lt;P&gt;

         If &lt;VAR&gt;header&lt;/VAR&gt; already exists and its contents
         are identical to what &lt;CODE&gt;AC_OUTPUT&lt;/CODE&gt; would
         put in it, it is left alone.  Doing this allows making some
         changes in the configuration without needlessly causing object
         files that depend on the header file to be recompiled.&lt;/P&gt;&lt;P&gt;

         Usually the input file is named
         &lt;TT&gt;&lt;VAR&gt;header&lt;/VAR&gt;.in&lt;/TT&gt;; however,
         you can override the input file name by appending to
         &lt;VAR&gt;header&lt;/VAR&gt; a colon-separated list of input
         files.  Examples:&lt;/P&gt;&lt;P&gt;

         &lt;TABLE&gt;&lt;tr&gt;&lt;td&gt;&amp;nbsp;&lt;/td&gt;&lt;td
         class=example&gt;&lt;pre&gt;
         AC_CONFIG_HEADERS([config.h:config.hin])
         AC_CONFIG_HEADERS([defines.h:defs.pre:defines.h.in:defs.post])
         &lt;/pre&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;/P&gt;&lt;P&gt;

          Doing this allows you to keep your file names acceptable to
         MS-DOS, or to prepend and/or append boilerplate to the file.
        </synopsis>
  </macro>
  <macro id="AH_VERBATIM">
      <prototype>
        <parameter content="key"/>
        <parameter content="template"/>
      </prototype>
        <synopsis>
          Tell &lt;CODE&gt;autoheader&lt;/CODE&gt; to include the
         &lt;VAR&gt;template&lt;/VAR&gt; as-is in the header template
         file.  This &lt;VAR&gt;template&lt;/VAR&gt; is associated with
         the &lt;VAR&gt;key&lt;/VAR&gt;, which is used to sort all the
         different templates and guarantee their uniqueness.  It should
         be a symbol that can be &lt;CODE&gt;AC_DEFINE&lt;/CODE&gt;'d.&lt;/P&gt;&lt;P&gt;

         For example:&lt;/P&gt;&lt;P&gt;

         &lt;TABLE&gt;&lt;tr&gt;&lt;td&gt;&amp;nbsp;&lt;/td&gt;&lt;td
         class=example&gt;&lt;pre&gt; AH_VERBATIM([_GNU_SOURCE], [/*
         Enable GNU extensions on systems that have them.  */ #ifndef
         _GNU_SOURCE # define _GNU_SOURCE #endif])
         &lt;/pre&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;
        </synopsis>
  </macro>
  <macro id="AH_TEMPLATE">
      <prototype>
        <parameter content="key"/>
        <parameter content="description"/>
      </prototype>
        <synopsis>
          Tell &lt;CODE&gt;autoheader&lt;/CODE&gt; to generate a template
         for &lt;VAR&gt;key&lt;/VAR&gt;.  This macro generates standard
         templates just like &lt;CODE&gt;AC_DEFINE&lt;/CODE&gt; when a
         &lt;VAR&gt;description&lt;/VAR&gt; is given.&lt;/P&gt;&lt;P&gt;

         For example:&lt;/P&gt;&lt;P&gt;

         &lt;TABLE&gt;&lt;tr&gt;&lt;td&gt;&amp;nbsp;&lt;/td&gt;&lt;td
         class=example&gt;&lt;pre&gt; AH_TEMPLATE([CRAY_STACKSEG_END],   
                  [Define to one of _getb67, GETB67, getb67             
         for Cray-2 and Cray-YMP systems.  This              function is
         required for alloca.c support              on those systems.])
         &lt;/pre&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;/P&gt;&lt;P&gt;

          will generate the following template, with the description
         properly justified.&lt;/P&gt;&lt;P&gt;

         &lt;TABLE&gt;&lt;tr&gt;&lt;td&gt;&amp;nbsp;&lt;/td&gt;&lt;td
         class=example&gt;&lt;pre&gt; /* Define to one of _getb67,
         GETB67, getb67 for Cray-2 and    Cray-YMP systems.  This
         function is required for alloca.c    support on those systems. 
         */ #undef CRAY_STACKSEG_END
         &lt;/pre&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;
        </synopsis>
  </macro>
  <macro id="AH_TOP">
      <prototype>
        <parameter content="text"/>
      </prototype>
        <synopsis>
          Include &lt;VAR&gt;text&lt;/VAR&gt; at the top of the header
         template file.
        </synopsis>
  </macro>
  <macro id="AH_BOTTOM">
      <prototype>
        <parameter content="text"/>
      </prototype>
        <synopsis>
          Include &lt;VAR&gt;text&lt;/VAR&gt; at the bottom of the header
         template file.
        </synopsis>
  </macro>
  <macro id="AC_CONFIG_COMMANDS">
      <prototype>
        <parameter content="tag..."/>
        <parameter content="[cmds]"/>
        <parameter content="[init-cmds]"/>
      </prototype>
        <synopsis>
          Specify additional shell commands to run at the end of
         &lt;TT&gt;config.status&lt;/TT&gt;, and shell commands to
         initialize any variables from
         &lt;CODE&gt;configure&lt;/CODE&gt;.  Associate the commands with
         &lt;VAR&gt;tag&lt;/VAR&gt;. Since typically the
         &lt;VAR&gt;cmds&lt;/VAR&gt; create a file,
         &lt;VAR&gt;tag&lt;/VAR&gt; should naturally be the name of that
         file.  If needed, the directory hosting
         &lt;VAR&gt;tag&lt;/VAR&gt; is created. This macro is one of the
         instantiating macros; see Configuration Actions.&lt;/P&gt;&lt;P&gt;

         Here is an unrealistic example:
         &lt;TABLE&gt;&lt;tr&gt;&lt;td&gt;&amp;nbsp;&lt;/td&gt;&lt;td
         class=example&gt;&lt;pre&gt; fubar=42
         AC_CONFIG_COMMANDS([fubar],                    [echo this is
         extra $fubar, and so on.],                    [fubar=$fubar])
         &lt;/pre&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;/P&gt;&lt;P&gt;

         Here is a better one:
         &lt;TABLE&gt;&lt;tr&gt;&lt;td&gt;&amp;nbsp;&lt;/td&gt;&lt;td
         class=example&gt;&lt;pre&gt; AC_CONFIG_COMMANDS([time-stamp],
         [date &gt;time-stamp])
         &lt;/pre&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;
        </synopsis>
  </macro>
  <macro id="AC_CONFIG_COMMANDS_PRE">
      <prototype>
        <parameter content="cmds"/>
      </prototype>
        <synopsis>
          Execute the &lt;VAR&gt;cmds&lt;/VAR&gt; right before creating
         &lt;TT&gt;config.status&lt;/TT&gt;.
        </synopsis>
  </macro>
  <macro id="AC_CONFIG_COMMANDS_POST">
      <prototype>
        <parameter content="cmds"/>
      </prototype>
        <synopsis>
          Execute the &lt;VAR&gt;cmds&lt;/VAR&gt; right after creating
         &lt;TT&gt;config.status&lt;/TT&gt;.
        </synopsis>
  </macro>
  <macro id="AC_CONFIG_LINKS">
      <prototype>
        <parameter content="dest:source..."/>
        <parameter content="[cmds]"/>
        <parameter content="[init-cmds]"/>
      </prototype>
        <synopsis>
           Make &lt;CODE&gt;AC_OUTPUT&lt;/CODE&gt; link each of the
         existing files &lt;VAR&gt;source&lt;/VAR&gt; to the
         corresponding link name &lt;VAR&gt;dest&lt;/VAR&gt;.  Makes a
         symbolic link if possible, otherwise a hard link if possible,
         otherwise a copy.  The &lt;VAR&gt;dest&lt;/VAR&gt; and
         &lt;VAR&gt;source&lt;/VAR&gt; names should be relative to the
         top level source or build directory.  This macro is one of the
         instantiating macros; see Configuration Actions.&lt;/P&gt;&lt;P&gt;

         For example, this call:&lt;/P&gt;&lt;P&gt;

         &lt;TABLE&gt;&lt;tr&gt;&lt;td&gt;&amp;nbsp;&lt;/td&gt;&lt;td
         class=example&gt;&lt;pre&gt;
         AC_CONFIG_LINKS(host.h:config/$machine.h                
         object.h:config/$obj_format.h)
         &lt;/pre&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;/P&gt;&lt;P&gt;

          creates in the current directory &lt;TT&gt;host.h&lt;/TT&gt; as
         a link to
         &lt;TT&gt;&lt;VAR&gt;srcdir&lt;/VAR&gt;/config/$machine.h&lt;/TT&gt;,
         and &lt;TT&gt;object.h&lt;/TT&gt; as a link to
         &lt;TT&gt;&lt;VAR&gt;srcdir&lt;/VAR&gt;/config/$obj_format.h&lt;/TT&gt;.&lt;/P&gt;&lt;P&gt;

         The tempting value &lt;samp&gt;.&lt;/samp&gt; for
         &lt;VAR&gt;dest&lt;/VAR&gt; is invalid: it makes it impossible
         for &lt;samp&gt;config.status&lt;/samp&gt; to guess the links to
         establish.&lt;/P&gt;&lt;P&gt;

         One can then run:
         &lt;TABLE&gt;&lt;tr&gt;&lt;td&gt;&amp;nbsp;&lt;/td&gt;&lt;td
         class=example&gt;&lt;pre&gt; ./config.status host.h object.h
         &lt;/pre&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;  to create the
         links.
        </synopsis>
  </macro>
  <macro id="AC_CONFIG_SUBDIRS">
      <prototype>
        <parameter content="dir ..."/>
      </prototype>
        <synopsis>
           Make &lt;CODE&gt;AC_OUTPUT&lt;/CODE&gt; run
         &lt;CODE&gt;configure&lt;/CODE&gt; in each subdirectory
         &lt;VAR&gt;dir&lt;/VAR&gt; in the given whitespace-separated
         list.  Each &lt;VAR&gt;dir&lt;/VAR&gt; should be a literal,
         i.e., please do not use:&lt;/P&gt;&lt;P&gt;

         &lt;TABLE&gt;&lt;tr&gt;&lt;td&gt;&amp;nbsp;&lt;/td&gt;&lt;td
         class=example&gt;&lt;pre&gt; if test "$package_foo_enabled" =
         yes; then   $my_subdirs="$my_subdirs foo" fi
         AC_CONFIG_SUBDIRS($my_subdirs)
         &lt;/pre&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;/P&gt;&lt;P&gt;

          because this prevents &lt;samp&gt;./configure
         --help=recursive&lt;/samp&gt; from displaying the options of the
         package &lt;CODE&gt;foo&lt;/CODE&gt;.  Rather, you should write:&lt;/P&gt;&lt;P&gt;

         &lt;TABLE&gt;&lt;tr&gt;&lt;td&gt;&amp;nbsp;&lt;/td&gt;&lt;td
         class=example&gt;&lt;pre&gt; if test "$package_foo_enabled" =
         yes; then   AC_CONFIG_SUBDIRS(foo) fi
         &lt;/pre&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;/P&gt;&lt;P&gt;

         If a given &lt;VAR&gt;dir&lt;/VAR&gt; is not found, an error is
         reported: if the subdirectory is optional, write:&lt;/P&gt;&lt;P&gt;

         &lt;TABLE&gt;&lt;tr&gt;&lt;td&gt;&amp;nbsp;&lt;/td&gt;&lt;td
         class=example&gt;&lt;pre&gt; if test -d $srcdir/foo; then  
         AC_CONFIG_SUBDIRS(foo) fi
         &lt;/pre&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;/P&gt;&lt;P&gt;

         If a given &lt;VAR&gt;dir&lt;/VAR&gt; contains
         &lt;CODE&gt;configure.gnu&lt;/CODE&gt;, it is run instead of
         &lt;CODE&gt;configure&lt;/CODE&gt;.  This is for packages that
         might use a non-Autoconf script
         &lt;CODE&gt;Configure&lt;/CODE&gt;, which can't be called
         through a wrapper &lt;CODE&gt;configure&lt;/CODE&gt; since it
         would be the same file on case-insensitive filesystems. 
         Likewise, if a &lt;VAR&gt;dir&lt;/VAR&gt; contains
         &lt;TT&gt;configure.in&lt;/TT&gt; but no
         &lt;CODE&gt;configure&lt;/CODE&gt;, the Cygnus
         &lt;CODE&gt;configure&lt;/CODE&gt; script found by
         &lt;CODE&gt;AC_CONFIG_AUX_DIR&lt;/CODE&gt; is used.&lt;/P&gt;&lt;P&gt;

         The subdirectory &lt;CODE&gt;configure&lt;/CODE&gt; scripts are
         given the same command line options that were given to this
         &lt;CODE&gt;configure&lt;/CODE&gt; script, with minor changes if
         needed, which include:&lt;/P&gt;&lt;P&gt;

         &lt;UL&gt; &lt;LI&gt; adjusting a relative path for the cache
         file;&lt;/P&gt;&lt;P&gt;

         &lt;LI&gt; adjusting a relative path for the source directory;&lt;/P&gt;&lt;P&gt;

         &lt;LI&gt; propagating the current value of
         &lt;CODE&gt;$prefix&lt;/CODE&gt;, including if it was defaulted,
         and if the default values of the top level and of the
         subdirectory &lt;TT&gt;configure&lt;/TT&gt; differ. &lt;/UL&gt;&lt;/P&gt;&lt;P&gt;

         This macro also sets the output variable
         &lt;CODE&gt;subdirs&lt;/CODE&gt; to the list of directories
         &lt;samp&gt;&lt;VAR&gt;dir&lt;/VAR&gt;
         &lt;small&gt;...&lt;/small&gt;&lt;/samp&gt;. 
         &lt;TT&gt;Makefile&lt;/TT&gt; rules can use this variable to
         determine which subdirectories to recurse into.&lt;/P&gt;&lt;P&gt;

         This macro may be called multiple times.
        </synopsis>
  </macro>
  <macro id="AC_PREFIX_DEFAULT">
      <prototype>
        <parameter content="prefix"/>
      </prototype>
        <synopsis>
          Set the default installation prefix to
         &lt;VAR&gt;prefix&lt;/VAR&gt; instead of
         &lt;TT&gt;/usr/local&lt;/TT&gt;.
        </synopsis>
  </macro>
  <macro id="AC_PREFIX_PROGRAM">
      <prototype>
        <parameter content="program"/>
      </prototype>
        <synopsis>
          If the user did not specify an installation prefix (using the
         &lt;samp&gt;--prefix&lt;/samp&gt; option), guess a value for it
         by looking for &lt;VAR&gt;program&lt;/VAR&gt; in
         &lt;CODE&gt;PATH&lt;/CODE&gt;, the way the shell does.  If
         &lt;VAR&gt;program&lt;/VAR&gt; is found, set the prefix to the
         parent of the directory containing
         &lt;VAR&gt;program&lt;/VAR&gt;, else default the prefix as
         described above (&lt;TT&gt;/usr/local&lt;/TT&gt; or
         &lt;CODE&gt;AC_PREFIX_DEFAULT&lt;/CODE&gt;).  For example, if
         &lt;VAR&gt;program&lt;/VAR&gt; is &lt;CODE&gt;gcc&lt;/CODE&gt;
         and the &lt;CODE&gt;PATH&lt;/CODE&gt; contains
         &lt;TT&gt;/usr/local/gnu/bin/gcc&lt;/TT&gt;, set the prefix to
         &lt;TT&gt;/usr/local/gnu&lt;/TT&gt;.
        </synopsis>
  </macro>
  <macro id="AC_DEFAULT_INCLUDES">
      <prototype>
        <parameter content="[include-directives]"/>
      </prototype>
        <synopsis>
          Expand to &lt;VAR&gt;include-directives&lt;/VAR&gt; if defined,
         otherwise to:&lt;/P&gt;&lt;P&gt;

         &lt;TABLE&gt;&lt;tr&gt;&lt;td&gt;&amp;nbsp;&lt;/td&gt;&lt;td
         class=example&gt;&lt;pre&gt; @group #include &lt;stdio.h&gt; #if
         HAVE_SYS_TYPES_H # include &lt;sys/types.h&gt; #endif #if
         HAVE_SYS_STAT_H # include &lt;sys/stat.h&gt; #endif #if
         STDC_HEADERS # include &lt;stdlib.h&gt; # include
         &lt;stddef.h&gt; #else # if HAVE_STDLIB_H #  include
         &lt;stdlib.h&gt; # endif #endif #if HAVE_STRING_H # if
         !STDC_HEADERS &amp;&amp; HAVE_MEMORY_H #  include
         &lt;memory.h&gt; # endif # include &lt;string.h&gt; #endif #if
         HAVE_STRINGS_H # include &lt;strings.h&gt; #endif #if
         HAVE_INTTYPES_H # include &lt;inttypes.h&gt; #else # if
         HAVE_STDINT_H #  include &lt;stdint.h&gt; # endif #endif #if
         HAVE_UNISTD_H # include &lt;unistd.h&gt; #endif @end group
         &lt;/pre&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;/P&gt;&lt;P&gt;

         If the default includes are used, then check for the presence of
         these headers and their compatibility, i.e., you don't need to
         run &lt;CODE&gt;AC_HEADERS_STDC&lt;/CODE&gt;, nor check for
         &lt;TT&gt;stdlib.h&lt;/TT&gt; etc.&lt;/P&gt;&lt;P&gt;

         These headers are checked for in the same order as they are
         included. For instance, on some systems
         &lt;TT&gt;string.h&lt;/TT&gt; and &lt;TT&gt;strings.h&lt;/TT&gt;
         both exist, but conflict.  Then
         &lt;CODE&gt;HAVE_STRING_H&lt;/CODE&gt; will be defined, but
         &lt;CODE&gt;HAVE_STRINGS_H&lt;/CODE&gt; won't.
        </synopsis>
  </macro>
  <macro id="AC_PROG_AWK">
      <prototype>
      </prototype>
        <synopsis>
           Check for &lt;CODE&gt;gawk&lt;/CODE&gt;,
         &lt;CODE&gt;mawk&lt;/CODE&gt;, &lt;CODE&gt;nawk&lt;/CODE&gt;,
         and &lt;CODE&gt;awk&lt;/CODE&gt;, in that order, and set output
         variable &lt;CODE&gt;AWK&lt;/CODE&gt; to the first one that is
         found. It tries &lt;CODE&gt;gawk&lt;/CODE&gt; first because that
         is reported to be the best implementation.
        </synopsis>
  </macro>
  <macro id="AC_PROG_EGREP">